# Write a program to print binary numbers from 1 to 10 using Queue. Use Queue class implemented in main tutorial. Binary sequence should look like,
#     1
#     10
#     11
#     100
#     101
#     110
#     111
#     1000
#     1001
#     1010
# Hint: Notice a pattern above. After 1 second and third number is 1+0 and 1+1. 4th and 5th number are second number (i.e. 10) + 0 and second number (i.e. 10) + 1.

# You also need to add front() function in queue class that can return the front element in the queue.

from collections import deque


class Queue:
    def __init__(self):
        self.buffer = deque()
    def enqueue(self, item):
        self.buffer.appendleft(item)
    def dequeue(self):
        if not self.is_empty():
            return self.buffer.pop()
        raise IndexError("Queue is empty")
    def front(self):
        if not self.is_empty():
            return self.buffer[-1] # front() function returns the front element of the queue, which is the last element in the buffer deque. If the queue is empty, it raises an IndexError with the message "Queue is empty".
        raise IndexError("Queue is empty")
    def is_empty(self):
        return len(self.buffer) == 0
    def size(self):
        return len(self.buffer)
    
    
q = Queue()

n = int(input("how many binary numbers you want to generate? "))

q.enqueue("1")

for i in range(n):
    front = q.front()  # Get the front element of the queue
    print(front)  # Print the front element (binary number)
    q.dequeue()  # Dequeue the front element
    q.enqueue(front + "0")  # Enqueue the front element with "0" appended
    q.enqueue(front + "1")  # Enqueue the front element with "1" appended
    
    # in detail explanation of the loop:
    # 1. The loop runs n times, where n is the number of binary numbers the user wants to generate.
    # 2. Inside the loop, the front element of the queue is retrieved using the front() method and stored in the variable front.
    # 3. The front element (which is a binary number) is printed to the console.            
    # 4. The front element is then removed from the queue using the dequeue() method.
    # 5. Two new binary numbers are generated by appending "0" and "1" to the front element, and these new binary numbers are enqueued back into the queue using the enqueue() method. This process continues until n binary numbers have been generated and printed.
    
    